### ISSUE TITLE
feat: integrate with cellxgene-schema-cli 

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cellxgene-ontology-guide#102]
- [x] remove [compute_ancestor_mapping.py](https://github.com/chanzuckerberg/single-cell-curation/blob/main/scripts/compute_mappings/compute_ancestor_mapping.py). It is no longer used.
- [x] update [ontology_bump_dry_run.py](https://github.com/chanzuckerberg/single-cell-curation/blob/main/scripts/schema_bump_dry_run_ontologies/ontology_bump_dry_run.py) to use ontology-guide. This should run whenever the ontology-guide version is updated.
- [x] remove [ontology_processing.py](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/scripts/ontology_processing.py) and update [readme.MD](https://github.com/chanzuckerberg/single-cell-curation/blob/main/cellxgene_schema_cli/scripts/readme.md).  This has been moved to ontology-guide
- [x] remove [ontology_files](https://github.com/chanzuckerberg/single-cell-curation/tree/main/cellxgene_schema_cli/cellxgene_schema/ontology_files). This is in ontology-guide now.
- [ ] replace [OntologyChecker](https://github.com/chanzuckerberg/single-cell-curation/blob/ffc99969981f92319a3b7aa7c5d3ced2a6cc49e3/cellxgene_schema_cli/cellxgene_schema/ontology.py#L113) with OntologyParser
- [ ] remap [cellzgene_schema_cli/cellxgene_schema/env.py](https://github.com/chanzuckerberg/single-cell-curation/blob/ffc99969981f92319a3b7aa7c5d3ced2a6cc49e3/cellxgene_schema_cli/cellxgene_schema/env.py#L4) as needed
- [ ] add ontology-guide as a requirement for the CLI

## Test Plan

- [ ] - write unit tests for:
- [ ]   - `Validator._has_forbidden_curie_ancestor` 
- [ ]   - `Validator._validate_curie_ancestors`
- [ ]   - `Validator._validate_curie_ontology`
- [ ]   - `Validator._validate_curie`
- [ ]   - `Validator._are_children_of`. 
- [ ]   - `AnnDataLabelAppender._get_ontology_term_label`
- [ ]   - Then verify the functions continue to work as expected integrating COG. 
- [ ] - 100 random datasets from production will be run through the validation and write labels and the output file will be compared to the file in prod. We are checking to see if their are any differences in the way ontology terms are checked. The output files should have the same hash as the original.
- [ ] - Run 1 dataset though the processing pipeline. We are check that the image built correctly, cellxgene-ontology-guide is used, and the resulting artifacts are generated without regression.
- [ ] - Run the ontology_bump_dry_run before 5.0.0 migration and make sure it's the same after integrating COG.
- [ ] - Parse the ontology term IDs from the index endpoint and run each against OntologyParser.get_term_labels and check if those lists are equal.

## Definition of Done

- [ ] A new release of CLI is created
- [ ] The cli validate datasets successfully.
- [ ] The portal processing pipeline can ingest datasets using the new CLI

**Comment by nayib-jose-gloria** [comment]
Dry-Run Changes Draft PR: https://github.com/chanzuckerberg/single-cell-curation/pull/813/files#diff-233106aaa7c288130bfcbe0e6a5ef2a02ae34294bc050271f999c983c53a3f33

**Comment by nayib-jose-gloria** [comment]
CLI Changes Draft PR: https://github.com/chanzuckerberg/single-cell-curation/pull/815

**Comment by nayib-jose-gloria** [comment]
Removing / renaming deprecated files PR: https://github.com/chanzuckerberg/single-cell-curation/pull/818

**Comment by Bento007** [comment]
Here is the [test](https://czi-sci.slack.com/archives/C05705D2JUS/p1710508791500299) for: 
> Run the ontology_bump_dry_run before 5.0.0 migration and make sure it's the same after integrating COG.

There may be a difference in the collections but the deprecated terms are the same which is what matters.
