### ISSUE TITLE
feat: integrate with portal

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cellxgene-ontology-guide#103]
## Approach

- [ ] remove [compute_tissue_and_cell_type_mappings.py](https://github.com/chanzuckerberg/single-cell-curation/blob/main/scripts/compute_mappings/compute_tissue_and_cell_type_mappings.py)
- [ ] direct frontend to download descendant mappings from cellxgene-ontology-main into [frontend/src/components/common/Filter/descendant_mappings](https://github.com/chanzuckerberg/single-cell-data-portal/tree/012e63c4a95f1300da80c74042989f449c6f246c/frontend/src/components/common/Filter/descendant_mappings)
- [ ] [these](https://github.com/chanzuckerberg/single-cell-data-portal/blob/012e63c4a95f1300da80c74042989f449c6f246c/.github/workflows/pull-latest-ontology-mappings.yml#L38-L39) s3 assets are not longer need. 
- [ ] refactor [backend/common/utils/ontology_mappings](https://github.com/chanzuckerberg/single-cell-data-portal/tree/012e63c4a95f1300da80c74042989f449c6f246c/backend/common/utils/ontology_mappings) to use ontology-guide
- [ ] verify https://github.com/chanzuckerberg/single-cell-data-portal/issues/6227 is addressed 

## Testing Plan
- A branch will be deploy to rdev, prod will be mirrored to this deployment, and a side by side comparison of filters and index endpoint will be done.
- e2e test pass.

## Definition of Done
- Verify that the frontend filters work as expected
- Verify that the dataportal index endpoint returns the correct response and is not too slow
- Verify the assets from COG are updated when redeploying the portal.

**Comment by nayib-jose-gloria** [comment]
Integrating with Portal Draft PR: https://github.com/chanzuckerberg/single-cell-data-portal/pull/6788

**Comment by Bento007** [comment]
>A branch will be deploy to rdev, prod will be mirrored to this deployment, and a side by side comparison of filters and index endpoint will be done.

There were differences between the frontend filters, but they were improvements from the original.
