### ISSUE TITLE
feat(API): The API downloads the Data Release during or after install.

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cellxgene-ontology-guide#13]
# Need:  
To streamline integration across products, the latest compatible data release is installed when the API is installed. This makes it easier for other services to stay up to date on the latest ontology without making changes to their code.

The package should also remain performant and compact. After downloading the JSON data release, convert it into a more python native file format.

# Depends_on:
- Create a first release
  - For testing the full functionality.
# DOD:
- The API must be aware of what version of the Data Release it is compatible with. When downloading the Data Release, only download the latest compatible version.
- Only download the Data Release once, and cache the files locally for future use.
- Implement fetching source repos + version tags from API + Tests 
- Can also run off a local all_ontology.json
- Can pin to a specific data release.
- Covert to python native file format Example: `pickle` 
- Delete remove original JSON.

**Comment by nayib-jose-gloria** [comment]
Changes to this ticket: Decided to implement such that we do NOT download a data version upon install; instead, users create an OntologyParser object for the schema_version they want to use ontology files for, and we will fetch + load that in-memory. Did not implement pickling (though we may revisit that decision in a future ticket)
