### ISSUE TITLE
Documentation release process

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cellxgene-ontology-guide#145]
document (in the repo, not docsite) the release process + changelog best practices for contributors

_Originally posted by @nayib-jose-gloria in https://github.com/chanzuckerberg/cellxgene-ontology-guide/pull/99#pullrequestreview-1958262721_

**Comment by nayib-jose-gloria** [comment]
dupe with https://github.com/chanzuckerberg/cellxgene-ontology-guide/issues/165
