### ISSUE TITLE
feat(API): Implement Curated Cell Class / Subclass Querying API (based on Pablo’s prototype)  + Tests

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cellxgene-ontology-guide#16]
# Depends on:
Implement must-haves of Generalized Ontology Querying API 

# DOD:

- Get Curated Cell Classes by Term ID*
- Get Curated Cell Classes by Term ID List*
- Get Curated Cell Subclasses by Term ID*
- Get Curated Cell Subclasses by Term ID List*
- List Curated Cell Classes
- List Curated Cell Subclasses

**Comment by nayib-jose-gloria** [comment]
dupe: same implementation as https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/cellxgene-ontology-guide/18
