### ISSUE TITLE
Update CELLxGENE Platform Technical Overview with Ontology Guide

### ISSUE THREAD

**Issue by metakuni** [chanzuckerberg/cellxgene-ontology-guide#88]
[CAN DO THIS LAST, BUT MUST DO!]

## Motivation

Keeping our [centralized platform overview doc](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0/edit#heading=h.7wimlorgnmka) updated will make it easier for engineers and stakeholders to find what they need in the future.

Updating this doc typically gets descoped at the end of projects and the doc keeps getting further and further outdated. 

## Definition of Done

Update [CELLxGENE Platform Technical Overview](https://docs.google.com/document/d/19IZbojtc7eofV75NnL5C6fCgBJB13KIswWNOn12xAa0/edit#heading=h.7wimlorgnmka) with relevant info for the Cellxgene Ontology Guide.

## Tasks

Detail the specific tasks that can be used to accomplish the desired changes.
If detailed steps cannot be provided at this time, please file a [Tech Proposal](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.7dvzhm7gqc3v) instead.

- [ ]
- [ ]

**Comment by metakuni** [comment]
Adding a `P0` label to indicate importance, but this can be done last.

**Comment by Bento007** [comment]
Complete
